name: Update submodules

on:
  push:
    branches:
      - 'main'

jobs:
  update-docs:
    environment: push
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          repository: stan-dev/docs
          submodules: recursive
          token: ${{ secrets.STAN_BOT_TOKEN }}

      - name: Push changes to stan-dev/docs
        run: |
          git config user.email "mc.stanislaw@gmail.com"
          git config user.name "Stan Jenkins"

          git submodule update --init --recursive --remote
          git add .
          git commit -m "Updating submodule quarto to ${{ github.sha }}"

          git push https://stan-buildbot:${{ secrets.STAN_BOT_TOKEN }}@github.com/stan-dev/docs master

  update-website:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          repository: stan-dev/stan-dev.github.io
          submodules: recursive
          token: ${{ secrets.STAN_BOT_TOKEN }}

      - name: Push changes to stan-dev/docs
        run: |
          git config user.email "mc.stanislaw@gmail.com"
          git config user.name "Stan Jenkins"

          git submodule update --init --recursive --remote
          git add .
          git commit -m "Updating submodule quarto to ${{ github.sha }}"

          git push https://stan-buildbot:${{ secrets.STAN_BOT_TOKEN }}@github.com/stan-dev/stan-dev.github.io quarto-${{ github.sha }}
          gh pr create --base master --head quarto-${{ github.sha }} --fill
        env:
          GITHUB_TOKEN: ${{ secrets.STAN_BOT_TOKEN }}
